# Generated by Django 6.0.3 on 2026-06-08 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0003_dthtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biller_code', models.CharField(max_length=20)),
                ('biller_name', models.CharField(max_length=100)),
                ('consumer_number', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('inspay_txid', models.CharField(blank=True, max_length=100, null=True)),
                ('inspay_opid', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failure', 'Failure')], default='pending', max_length=10)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_amount', models.CharField(blank=True, max_length=20, null=True)),
                ('due_date', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricity_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
