# Generated by Django 6.0.3 on 2026-06-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge', '0006_broadbandtransaction_insurancetransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTHPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.CharField(max_length=20)),
                ('operator_name', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity', models.CharField(max_length=50)),
                ('channels', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('hindi', 'Hindi'), ('regional', 'Regional'), ('sports', 'Sports'), ('hd', 'HD'), ('combo', 'Combo'), ('ott', 'OTT'), ('basic', 'Basic')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
