# Generated by Django 6.0.3 on 2026-06-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otp_attempts_otp_is_expired_user_failed_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='sim_operator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
