# Generated by Django 6.0.3 on 2026-06-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profile_pic_user_sim_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
