# Generated by Django 6.0.3 on 2026-06-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Terms and Conditions'), ('privacy', 'Privacy Policy'), ('refund', 'Refund and Cancellation Policy')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content_html', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('effective_date', models.DateField()),
                ('last_updated', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
