# Generated by Django 6.0.3 on 2026-04-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='min_points_to_unlock',
            field=models.IntegerField(default=0),
        ),
    ]
