from django.urls import path
from .views import (
    OperatorListView,
    CircleListView,
    PlanListView,
    InitiateRechargeView,
    RechargeStatusView,
    InspayBalanceView,
    RechargeHistoryView,
    ActivePlanView,
    InspayWebhookView,
    DTHOperatorListView,
    InitiateDTHRechargeView,
    DTHHistoryView,
    ElectricityBillerListView,
    FetchElectricityBillView,
    PayElectricityBillView,
    ElectricityHistoryView,
    FastagOperatorListView,
    InitiateFastagRechargeView,
    FastagHistoryView,
    BroadbandOperatorListView,
    InitiateBroadbandRechargeView,
    BroadbandHistoryView,
    LPGOperatorListView,
    InitiateLPGRechargeView,
    LPGHistoryView,
    WaterBillerListView,
    PayWaterBillView,
    WaterHistoryView,
    InsuranceProviderListView,
    PayInsurancePremiumView,
    InsuranceHistoryView,
)

urlpatterns = [
    path('operators/', OperatorListView.as_view(), name='operators'),
    path('circles/', CircleListView.as_view(), name='circles'),
    path('plans/', PlanListView.as_view(), name='plans'),
    path('initiate/', InitiateRechargeView.as_view(), name='initiate-recharge'),
    path('status/', RechargeStatusView.as_view(), name='recharge-status'),
    path('balance/', InspayBalanceView.as_view(), name='inspay-balance'),
    path('history/', RechargeHistoryView.as_view(), name='recharge-history'),
    path('active-plan/', ActivePlanView.as_view(), name='active-plan'),
    path('webhook/', InspayWebhookView.as_view(), name='inspay-webhook'),
    path('dth/operators/', DTHOperatorListView.as_view(), name='dth-operators'),
    path('dth/initiate/', InitiateDTHRechargeView.as_view(), name='dth-initiate'),
    path('dth/history/', DTHHistoryView.as_view(), name='dth-history'),
    path('electricity/billers/', ElectricityBillerListView.as_view(), name='electricity-billers'),
    path('electricity/fetch-bill/', FetchElectricityBillView.as_view(), name='electricity-fetch-bill'),
    path('electricity/pay/', PayElectricityBillView.as_view(), name='electricity-pay'),
    path('electricity/history/', ElectricityHistoryView.as_view(), name='electricity-history'),
    path('fastag/operators/', FastagOperatorListView.as_view(), name='fastag-operators'),
    path('fastag/initiate/', InitiateFastagRechargeView.as_view(), name='fastag-initiate'),
    path('fastag/history/', FastagHistoryView.as_view(), name='fastag-history'),
    path('broadband/operators/', BroadbandOperatorListView.as_view(), name='broadband-operators'),
    path('broadband/initiate/', InitiateBroadbandRechargeView.as_view(), name='broadband-initiate'),
    path('broadband/history/', BroadbandHistoryView.as_view(), name='broadband-history'),
    path('lpg/operators/', LPGOperatorListView.as_view(), name='lpg-operators'),
    path('lpg/initiate/', InitiateLPGRechargeView.as_view(), name='lpg-initiate'),
    path('lpg/history/', LPGHistoryView.as_view(), name='lpg-history'),
    path('water/billers/', WaterBillerListView.as_view(), name='water-billers'),
    path('water/pay/', PayWaterBillView.as_view(), name='water-pay'),
    path('water/history/', WaterHistoryView.as_view(), name='water-history'),
    path('insurance/providers/', InsuranceProviderListView.as_view(), name='insurance-providers'),
    path('insurance/pay/', PayInsurancePremiumView.as_view(), name='insurance-pay'),
    path('insurance/history/', InsuranceHistoryView.as_view(), name='insurance-history'),
]